### ISSUE TITLE
Resolve contrasting effect on entities

### ISSUE THREAD

**Issue by ivantjh** [CIA-hideout/pongstar#63]
Enlarge + Shrink
Boost + Slow

**Comment by chesterhow** [comment]
what happens when these occur atm?

**Comment by ivantjh** [comment]
Hit enlarge -> Entity grows, enlarge timer running
Hit shrink -> Entity shrinks, enlarge and shrink effect timers run
Enlarge timer ends, entity grows back to normal size. When shrink timer runs out, does nothing.

**Comment by chesterhow** [comment]
Do check for contrasting effects?

- Hits shrink
- Check for enlarge effect
- Remove enlarge effect immediately
- Run shrink effect

**Comment by ivantjh** [comment]
Yeap thats what I did

**Comment by elcoms** [comment]
Smart boi
